spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:backofficeDb
#    url: jdbc:h2:file://home/hj/zerobase/springboot-JPA-practice/backofficeDb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mustache:
    suffix: .html

  extra:
    key: c
    kakao: 7

  mail:
    username: @gmail.com
    password: qwerty
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

naver-api:
  client-id: a
  client-secret: a

